

#   Screen info
SCREEN_HEIGHT = 700
SCREEN_WIDTH = int(SCREEN_HEIGHT * 1.6)
SCREEN_RES = (SCREEN_WIDTH, SCREEN_HEIGHT)

#   Colours
BLACK = (0,0,0)
GREY = (50,50,50)
GREEN = (0,255,0)
WHITE = (255,255,255)
BEIGE = (242,234,224)

# Box info
BORDER_SIZE = 420
BOX_SIZE = 410
BLOCK_SIZE = BORDER_SIZE / 9
top_left_x = (SCREEN_WIDTH / 2) - (BORDER_SIZE / 2)
top_left_y = (SCREEN_HEIGHT / 2) - (BORDER_SIZE / 2)
top_right_x = (SCREEN_WIDTH / 2) + (BORDER_SIZE / 2)
top_right_y = (SCREEN_HEIGHT / 2) - (BORDER_SIZE / 2)
bottom_left_x = (SCREEN_WIDTH / 2) - (BORDER_SIZE / 2)
bottom_left_y = (SCREEN_HEIGHT / 2) + (BORDER_SIZE / 2)